include:
  - backend/compose-backend.yaml

services:

  database:
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "12306"
    environment:
      MYSQL_TCP_PORT: 12306
      MYSQL_UNIX_PORT: 12306
    networks:
      - nginx-proxy-network

  backend:
    deploy:
      resources:
        limits:
          memory: 1gb
        reservations:
          memory: 500M
    expose:
      - "9090"
    networks:
      - nginx-proxy-network

volumes:
  mariadb_data:

networks:
  nginx-proxy-network:
    external: true
