include:
  - infra/compose-database.yaml
  - backend/compose-backend.yaml

name: stage

services:

  database:
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - nginx-proxy-network

  mvc:
    deploy:
      resources:
        limits:
          memory: 1gb
        reservations:
          memory: 500M
    expose:
      - "8080"
    networks:
      - nginx-proxy-network
    depends_on:
      database:
        condition: service_healthy
        restart: true

  api:
    deploy:
      resources:
        limits:
          memory: 1gb
        reservations:
          memory: 500M
    expose:
      - "8080"
    networks:
      - nginx-proxy-network
    depends_on:
      database:
        condition: service_healthy
        restart: true

volumes:
  mariadb_data:

networks:
  nginx-proxy-network:
    external: true
