
services:

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf:ro
      - ${HTACCESS_FILE}:/etc/nginx/.htpasswd
      - ${PROD_STATIC_DIR}:/static:ro
      - ${STAGE_STATIC_DIR}:/static:ro
      - ${PUBLIC_DIR}:/public:ro
      - ${SSL_KEY_LOCATION}:/certs/key.pem:ro
      - ${SSL_CERT_LOCATION}:/certs/cert.pem:ro
      - ${SSL_NGINX_OPTIONS_LOCATION}:/certs/options-ssl-nginx.conf
      - ${SSL_DHPARAMS_LOCATION}:/certs/ssl-dhparams.pem
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true