include:
  - infra/compose-database.yaml
  - backend/compose-backend.yaml
  - infra/compose-proxy.yaml

name: local

services:

  database:
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "12306"
    environment:
      MYSQL_TCP_PORT: 12306
      MYSQL_UNIX_PORT: 12306

  mvc:
    expose:
      - "8080"
    depends_on:
      database:
        condition: service_healthy
        restart: true

  api:
    expose:
      - "8080"
    depends_on:
      database:
        condition: service_healthy
        restart: true

  webserver:
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx-local.conf:/etc/nginx/nginx.conf:ro
      - ./backend/static/:/static:ro

volumes:
  mariadb_data: