include:
  - ./services/compose-database.yaml
  - ./services/compose-webserver.yaml

services:
  backend:
    build: ./backend
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS}
      - EMAIL_RECIPIENT_ADDRESS=${EMAIL_RECIPIENT_ADDRESS}
    deploy:
      resources:
        limits:
          memory: 1gb
        reservations:
          memory: 500M
    expose:
      - "8080"
    depends_on:
      database:
        condition: service_healthy
        restart: true
