include:
  - backend/compose-backend.yaml

services:

  database:
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - nginx-proxy-network

  backend:
    deploy:
      resources:
        limits:
          memory: 1gb
        reservations:
          memory: 500M
    expose:
      - "8080"
    networks:
      - nginx-proxy-network

volumes:
  mariadb_data:

networks:
  nginx-proxy-network:
    external: true