include:
  - infra/compose-proxy.yaml

name: proxy

services:

  webserver:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/conf.d:/etc/nginx/conf.d:ro
      - ${HTACCESS_FILE}:/etc/nginx/.htpasswd
      - ${PROD_STATIC_DIR}:/prod/static:ro
      - ${STAGE_STATIC_DIR}:/stage/static:ro
      - ${PUBLIC_DIR}:/public:ro
      - ${SSL_KEY_LOCATION}:/certs/key.pem:ro
      - ${SSL_CERT_LOCATION}:/certs/cert.pem:ro
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
