###############################
# SSH configuration file      #
# place in:                   #
# <ssh>/sshd_config.d/        #
###############################

PasswordAuthentication no
PermitRootLogin no
AllowUsers ubuntu
PermitEmptyPasswords no
LoginGraceTime 10
MaxAuthTries 3
