DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    published_date TIMESTAMP NOT NULL,
    is_draft BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL
);

