###
# Base nginx configuration
###
  x-nginx-base: &nginx-base
    image: nginx:alpine
    container_name: webserver
    ports:
      - "80:80"
    depends_on:
      - backend

  services:
    webserver-dev:
      <<: *nginx-base
      profiles: [ dev ]
      volumes:
        - ./nginx/nginx-local.conf:/etc/nginx/nginx.conf:ro
        - ../backend/static/:/static:ro

    webserver-prod:
      <<: *nginx-base
      profiles: [ prod ]
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf:ro
        - ../backend/static/:/static:ro
        - ${HTACCESS_FILE}:/etc/nginx/${HTACCESS_FILE}:ro
        - ${SSL_KEY_LOCATION}:/certs/key.pem:ro
        - ${SSL_CERT_LOCATION}:/certs/cert.pem:ro
        - ${SSL_NGINX_OPTIONS_LOCATION}:/certs/options-ssl-nginx.conf
        - ${SSL_DHPARAMS_LOCATION}:/certs/ssl-dhparams.pem
