events {}

http {
    include     /etc/nginx/mime.types;
    error_log   /dev/stdout info;
    limit_req_zone $binary_remote_addr zone=5rs:10m rate=1r/s;

    server {
        listen 80;

        error_page 429 /429.html;
        error_page 502 /502.html;

        location /static/ {
            # note to self: when using location and alias like that, the actual location bit gets stripped, ie:
            # foobar.com/static/css/styles.css
            # with the configuration like that:
            # alias /usr/share/nginx/html
            # becomes this on the file system:
            # /usr/share/nginx/htmlcss/styles.css <- notice slashes matter and static gets replaced by the alias config
            # So, to ensure consistency, set the compose setting to copying the full directory and then just map to it
            # directly in here
            alias /static/;
        }

        location ~ ^/(429|502)\.html$ {
            root /static/html;
        }

        location / {
            limit_req zone=5rs nodelay;
            limit_req_status 429;

            proxy_pass http://backend:8080;
            proxy_intercept_errors on;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

    }

    server {
            listen 80;
            server_name api.localhost;

            location / {
                proxy_pass http://backend:8080/api/;

                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
}