events {}

http {
    include     /etc/nginx/mime.types;
    error_log   /dev/stdout info;

    # Rate limit configurations
    ## 5 requests per second
    ### This is a very strict rate limit and should only be applied to actual endpoints
    ### Make sure to define locations for static files that are not bound by this limit
    limit_req_zone $binary_remote_addr zone=5rs:10m rate=5r/s;

    server {
     	auth_basic "Restricted";
     	auth_basic_user_file /etc/nginx/.htaccess;

    	server_name dimitar.fr;

    	location / {
    		limit_req zone=5rs nodelay;
            limit_req_status 429;

    		proxy_pass http://backend:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    		proxy_set_header X-Forwarded-Proto $scheme;
    	}

    	location /static/ {
            expires 1M;
            autoindex on;

            # note to self: when using location and alias like that, the actual location bit gets stripped, ie:
            # foobar.com/static/css/styles.css
            # with the configuration like that:
            # alias /usr/share/nginx/html
            # becomes this on the file system:
            # /usr/share/nginx/htmlcss/styles.css <- notice slashes matter and static gets replaced by the alias config
            # So, to ensure consistency, set the compose setting to copying the full directory and then just map to it
            # directly in here
            alias /static/;
        }

        # Where Certbot will generate the HTTP challenges for the certificate renewals
        # TODO: tweak this
    	location /.well-known/ {
    		alias /home/ubuntu/website/.well-known/;
    	}

        # Certbot configuration for the Let's Encrypt certificates
        # Important to note that nginx expects that the certificates will already be present when starting up
        listen 443 ssl;
        ssl_certificate /certs/cert.pem;
        ssl_certificate_key /certs/key.pem;
        include /certs/options-ssl-nginx.conf;
        ssl_dhparam /certs/ssl-dhparams.pem;

    }


    server {
        if ($host = dimitar.fr) {
            return 301 https://$host$request_uri;
        } # managed by Certbot
        if ($host = www.dimitar.fr) {
    	    return 301 https://$host$request_uri;
        }

    	server_name dimitar.fr;
    	listen 80;
        return 404; # managed by Certbot
    }
}