# Rate limit configurations
## 5 requests per second
### This is a very strict rate limit and should only be applied to actual endpoints
### Make sure to define locations for static files that are not bound by this limit
### IMPORTANT -> $binary_remote_addr + Rootless Docker
###     It will only work if the driver has been updated:
###     https://docs.docker.com/engine/security/rootless/troubleshoot/#docker-run--p-does-not-propagate-source-ip-addresses
limit_req_zone $binary_remote_addr zone=5rs:10m rate=5r/s;
