spring.application.name=web

# Enforce use of UTC for Hibernate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

logging.level.org.springframework.security=TRACE

# Do not include the stack trace on exceptions
server.error.include-stacktrace = never

spring.datasource.url=jdbc:mariadb://localhost/blog
spring.datasource.username=test
spring.datasource.password=test
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
org.mariadb.jdbc=DEBUG

server.servlet.session.cookie.path=/
server.servlet.session.cookie.same-site=strict
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true

gg.jte.developmentMode=false
gg.jte.usePrecompiledTemplates=true
gg.jte.template-location=src/main/jte

server.forward-headers-strategy=framework
