---

- name: Verify SSH key connection
  hosts: personal

  vars:
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root

  tasks:
    - name: Disable SSH password auth
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/99-disable-password.conf
        src: ./files/99-disable-password.conf
        owner: root
        mode: '644'

    - name: Reload SSH
      ansible.builtin.service:
        name: ssh
        state: reloaded

    - name: Get post-reload state
      ansible.builtin.command: systemctl is-active ssh
      register: sshd_status

    - name: Record state
      ansible.builtin.debug:
        msg: "SSH daemon post-restart state: {{ sshd_status['stdout'] }}"

    - name: Verify state
      ansible.builtin.fail:
        msg: SSH daemon has failed to reload post-config deployment
      when: sshd_status['stdout'] != "active"
