---

- name: Create Docker user & group
  hosts: personal

  vars:
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root

  tasks:
    - name: Create Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Create Docker user
      ansible.builtin.user:
        name: docker
        create_home: yes
        shell: /bin/bash
        groups: docker

    - name: Deploy public key
      ansible.posix.authorized_key:
        user: docker
        state: present
        key: "{{ lookup('file', pubkey_path) }}"
      when: pubkey_path != ""

    - name: Add user to Allowed SSH users
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config.d/99-disable-password.conf
        search_string: "AllowUsers ubuntu"
        line: "AllowUsers ubuntu docker"

    - name: Reload SSH
      ansible.builtin.service:
        name: ssh
        state: reloaded

    - name: Get post-reload state
      ansible.builtin.command: systemctl is-active ssh
      register: sshd_status

    - name: Record state
      ansible.builtin.debug:
        msg: "SSH daemon post-restart state: {{ sshd_status['stdout'] }}"

    - name: Verify state
      ansible.builtin.fail:
        msg: SSH daemon has failed to reload post-config deployment
      when: sshd_status['stdout'] != "active"
