@template.base(
title = "About Dimitar",
head = @`<link rel="stylesheet" type="text/css" href="/static/css/pages/about.css">`,
content = @`
    <div class="main-content">
        <h2>too long; didn't read</h2>
        <p>Name: Dimitar Ivanov</p>
        <p>Online Alias: Winter</p>
        <p>Date of Birth: July, 1991</p>
        <p>
            City of Birth:
            <a class="highlight" target="_blank" href="https://en.wikipedia.org/wiki/Kardzhali">
               Kardzhali, Bulgaria
            </a>
        </p>
        <p>Current Location:
            <a class="highlight" target="_blank" href="https://en.wikipedia.org/wiki/Vaucluse">
                Vaucluse, Provence-Alpes-Côte d'Azur, France
            </a>
        </p>
        <p>Occupation: Tech Guy</p>
        <h2>too long; did read</h2>
        <p>
            I was born and raised in Kardzhali, Bulgaria, a small and quiet town in the South of the country. I've spent
            my teenage years surrounded by friends, family, neighbors, shop clerks, postmen, something which I believe
            shaped the need now, in my adult life, to always seek out this feeling of community, of knowing the people
            with whom I share a street, the people working at the local store, the postman, anyone and everyone in my
            immediate surrounding.
        </p>
        <p>
            Never been to uni, because I couldn't afford it, but on the upside, I started working immediately after
            graduating from high school, which is the only reason for my long experience in the IT industry. Professionally,
            I've occupied multiple positions, from helpdesk, through QA, to operations and software development. At the
            core of it all, it's just my insatiable love for computers.
        </p>
        <p>
            Ever since I could get my hands on an internet-connected computer, I've always sought out online communities,
            mainly related to the video games I've played. In my early teenage years, I played a game called
            <a class="highlight" target="_blank" href="https://en.wikipedia.org/wiki/Freelancer_(video_game)">Freelancer</a>
            which connected me with people from all over the world. Nowadays, unfortunately, many of those people exist
            just in my memories, due to long-lost contact, but sometimes I find comfort in reminding myself of how open
            and passion driven those early days online were.
        </p>
        <p>
            I left my hometown for the UK in 2017, and since then I've been stuck in a limbo where I neither fully belong
            to the country I reside in, nor in the country where I was born and raised.
        </p>
        <p>
            Since early 2025, I've been living with my partner in a small village in the South of France, trying to again
            find myself in a new and unknown environment.
        </p>
        <p>
            Given that this is a personal website and I believe it should be about personal stuff, outside of work,
            I greatly enjoy, in no particular order:
        </p>
        <ul>
            <li>mountain biking</li>
            <li>reading</li>
            <li>music</li>
            <li>board games</li>
            <li>petting cats</li>
            <li>petting dogs</li>
            <li>flowers</li>
            <li>Formula 1</li>
            <li>video games</li>
        </ul>
        <p>
            Needless to say, anything posted on here does not reflect the views and opinions of my employer, yada yada.
            Why on Earth would it? It's my own website. Having said that, everything posted on this website is something
            I've written myself, it is not the product of an AI; I think I threw up in my mouth a little bit just for having
            to write that.
        </p>
        <h2>About this Site</h2>
        <p>
            This site is hosted on
            <a class="highlight" target="_blank" href="https://www.hetzner.com/">Hetzner</a>, it doesn't collect any data
            about you because I don't give a fuck about collecting data. It uses some cookies but nothing used to profile
            or analyze you. Your IP address might be saved if you interact with the Guestbook but that's just me trying to
            reduce the amount of potential spam I might have to deal with.
        </p>
        <p>
            The site is built using Spring Boot with JTE (Java Template Engine). Originally, I was planning on going for
            the full-on enterprise experience of having a Spring BE and an Angular FE, but I figured I didn't want to make
            you, my dear reader, load a shitton of JavaScript just to read a dumbass article.
        </p>
        <p>
            The source code for this site can be found on my GitHub. Any feedback is always welcome - being a complete
            self-learner, I highly doubt everything I've created is perfect (or even close to it).
        </p>
        <h2>Anything and Everything</h2>
        <p>
            My mailbox is open, whether it's just for a chat, for feedback or for screaming into the void (although you
            can probably use /dev/null for that). You can use the contact form on here or e-mail me directly at
            <a class="highlight" href="mailto:me@dimitar.fr">me@dimitar.fr</a>
        </p>
    </div>
`
)