@template.base(
title = "About Dimitar",
head = @`<link rel="stylesheet" type="text/css" href="css/pages/about.css">`,
content = @`
    <div class="main-content">
        <h2>tl;dr</h2>
        <p>Name: Dimitar Ivanov</p>
        <p>Online Alias: Winter</p>
        <p>Date of Birth: July, 1991</p>
        <p>
            City of Birth:
            <a class="highlight" target="_blank" href="https://en.wikipedia.org/wiki/Kardzhali">
               Kardzhali, Bulgaria
            </a>
        </p>
        <p>Current Location:
            <a class="highlight" target="_blank" href="https://en.wikipedia.org/wiki/Vaucluse">
                Vaucluse, Provence-Alpes-Côte d'Azur, France
            </a>
        </p>
        <p>Occupation: Tech Guy</p>
        <h2>About this Site</h2>
        <p>
            This site is hosted on
            <a class="highlight" target="_blank" href="https://www.hetzner.com/">
                Hetzner
            </a>
            , it doesn't collect any data about you because I don't give a fuck about collecting data. It uses some cookies
            but nothing used to profile or analyze you. Your IP address might be saved if you interact with the Guestbook
            but that's just me trying to reduce the amount of potential spam I might have to deal with.
        </p>
        <p>
            The site is built using Spring Boot with JTE (Java Template Engine) because I wanted so. The source code for
            this site can be found on my GitHub. Any feedback is always welcome.
        </p>
        <h2>Anything and Everything</h2>
        <p>
            My mailbox is open, whether it's just for a chat, for feedback or for screaming into the void (although you
            can probably use /dev/null for that). You can use the contact form on here or e-mail me directly at
            <a class="highlight" href="mailto:me@dimitar.fr">me@dimitar.fr</a>
        </p>
    </div>
`
)