
@template.base(
title = "Dimitar's Now",
head = @`<link rel="stylesheet" href="css/pages/now.css">`,
content = @`
    <div class="now-body">
        <p class="description">
            This page is inspired by Derek Sivers' "now", see
            <a class="highlight" target="_blank" href="https://nownownow.com/about">nownownow</a>
            for more information on how to create your own!
        </p>
        <h2>What am I doing right now?</h2>
        <div class="last-updated">
            April, 2026
        </div>
        <p>
            Currently building this site from the ground up. Also continuing my hunt for a job in France, which hasn't been
            going great, but I'm trying to keep positive.
        </p>
        <p>
            Outside of that, trying to keep mountain biking as often as possible, reading (check out my
            <a class="highlight" target="_blank" href="https://www.goodreads.com/user/show/136298234-dimitar">
                Goodreads
            </a>
            account) and still trying to kick smoking down the drain.
        </p>
    </div>
`
)